-- 000013_create_sessions.up.sql
--
-- Sessions table for browser-based authentication.
-- Each row represents an active login session. When a player logs in via
-- the HTML form, we create a session here and send the session ID as an
-- HttpOnly cookie. On each request, the middleware looks up the session
-- to identify the player — no JWT needed for browser flows.
--
-- WHY SERVER-SIDE SESSIONS (not JWT-in-cookie)?
--   JWTs are stateless — once issued, they cannot be revoked until they expire.
--   Server-side sessions can be destroyed immediately (logout, password change,
--   admin force-logout). This teaches the difference between stateless and
--   stateful authentication, which is a core concept in web security.

CREATE TABLE sessions (
    -- id is a cryptographically random 64-character hex string (32 bytes).
    -- Using TEXT instead of UUID because session IDs are generated by our code
    -- (crypto/rand), not by PostgreSQL's gen_random_uuid().
    id TEXT PRIMARY KEY,

    -- player_id links this session to a player. ON DELETE CASCADE means
    -- deleting a player automatically destroys all their sessions.
    player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,

    -- role is cached from the player at login time. This avoids a JOIN on
    -- every request — the middleware can read the role directly from the session.
    -- If the player's role changes, existing sessions keep the old role until
    -- they expire or the player re-logs in.
    role TEXT NOT NULL,

    -- username is cached from the player at login time. Used to display the
    -- player's name in the navbar without an extra DB lookup on every page.
    username TEXT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- expires_at is when this session becomes invalid. The middleware checks
    -- this on every request and rejects expired sessions. A background job
    -- can clean up expired rows periodically.
    expires_at TIMESTAMPTZ NOT NULL
);

-- Index for looking up all sessions belonging to a player.
-- Used when destroying all sessions on logout-everywhere or password change.
CREATE INDEX idx_sessions_player_id ON sessions(player_id);

-- Index for efficiently cleaning up expired sessions.
-- A periodic DELETE WHERE expires_at < now() uses this index.
CREATE INDEX idx_sessions_expires_at ON sessions(expires_at);
