// Package session — Database / Repository layer for sessions.
//
// This file is ONLY responsible for:
//   - Inserting, selecting, and deleting session rows in PostgreSQL
//   - Returning domain types (Session) to the service layer
//
// It must NOT contain business logic (e.g. "is this session expired?") or HTTP code.
package session

import (
	// --- Standard library ---
	"context" // for passing cancellation and deadlines to DB queries
	"fmt"     // for wrapping errors with context

	// --- Third-party ---
	"github.com/jackc/pgx/v5"         // PostgreSQL driver — pgx.ErrNoRows for "not found" detection
	"github.com/jackc/pgx/v5/pgxpool" // PostgreSQL connection pool
)

// SessionRepository handles all database operations for sessions.
// It follows the same pattern as PlayerRepository and TeamRepository:
// the struct holds a connection pool, and each method executes a single query.
type SessionRepository struct {
	// db is the connection pool to PostgreSQL, shared across the application.
	db *pgxpool.Pool
}

// NewSessionRepository creates a SessionRepository with the given connection pool.
func NewSessionRepository(pool *pgxpool.Pool) *SessionRepository {
	return &SessionRepository{db: pool}
}

// Compile-time check: ensure SessionRepository implements the Repository interface
// defined in service.go. If a method is missing or has the wrong signature,
// this line causes a compile error — catching the mistake before runtime.
//
// SYNTAX: var _ Interface = (*ConcreteType)(nil)
//   - var _ discards the value (we don't need it, just the type check)
//   - (*ConcreteType)(nil) creates a nil pointer of the concrete type
//   - The assignment checks that the nil pointer satisfies the interface
var _ Repository = (*SessionRepository)(nil)

// Create inserts a new session into the database.
// The session ID, player ID, role, username, and expiry are all set by the service layer.
func (r *SessionRepository) Create(ctx context.Context, s *Session) error {
	// INSERT with all session fields. The ID is generated by the service (crypto/rand),
	// not by PostgreSQL's gen_random_uuid(), because session IDs are hex strings.
	_, err := r.db.Exec(ctx, `
		INSERT INTO sessions (id, player_id, role, username, created_at, expires_at)
		VALUES ($1, $2, $3, $4, $5, $6)
	`, s.ID, s.PlayerID, s.Role, s.Username, s.CreatedAt, s.ExpiresAt)
	if err != nil {
		return fmt.Errorf("SessionRepository.Create: %w", err)
	}
	return nil
}

// GetByID fetches a session by its ID.
// Returns ErrSessionNotFound if no session with that ID exists.
func (r *SessionRepository) GetByID(ctx context.Context, id string) (*Session, error) {
	var s Session
	// QueryRow returns at most one row. We scan all fields into the Session struct.
	err := r.db.QueryRow(ctx, `
		SELECT id, player_id, role, username, created_at, expires_at
		FROM sessions
		WHERE id = $1
	`, id).Scan(&s.ID, &s.PlayerID, &s.Role, &s.Username, &s.CreatedAt, &s.ExpiresAt)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, ErrSessionNotFound
		}
		return nil, fmt.Errorf("SessionRepository.GetByID: %w", err)
	}
	return &s, nil
}

// Delete removes a single session by its ID.
// Used for logout — destroys only the current session.
func (r *SessionRepository) Delete(ctx context.Context, id string) error {
	_, err := r.db.Exec(ctx, `DELETE FROM sessions WHERE id = $1`, id)
	if err != nil {
		return fmt.Errorf("SessionRepository.Delete: %w", err)
	}
	return nil
}

// DeleteByPlayerID removes all sessions for a given player.
// Used for "logout everywhere" or when a player changes their password.
func (r *SessionRepository) DeleteByPlayerID(ctx context.Context, playerID string) error {
	_, err := r.db.Exec(ctx, `DELETE FROM sessions WHERE player_id = $1`, playerID)
	if err != nil {
		return fmt.Errorf("SessionRepository.DeleteByPlayerID: %w", err)
	}
	return nil
}

// DeleteExpired removes all sessions whose expires_at is in the past.
// Called periodically to prevent the sessions table from growing indefinitely.
func (r *SessionRepository) DeleteExpired(ctx context.Context) error {
	_, err := r.db.Exec(ctx, `DELETE FROM sessions WHERE expires_at < now()`)
	if err != nil {
		return fmt.Errorf("SessionRepository.DeleteExpired: %w", err)
	}
	return nil
}
