// Package auth contains all code for player authentication and identity.
//
// This package is responsible for:
//   - Registering new player accounts (POST /auth/register)
//   - Authenticating players and issuing JWTs (POST /auth/login)
//   - Returning the current player's profile (GET /auth/me)
//
// It owns the `players` table in the database.
// The three files in this package each handle one layer:
//   - model.go      — data shapes (structs and request/response types)
//   - repository.go — database queries
//   - service.go    — business logic
//   - handler.go    — HTTP request/response handling
package auth

import (
	// --- Standard library ---
	"time" // for the CreatedAt and UpdatedAt timestamps on the Player struct
)

// Player is the internal representation of a registered user.
// It maps directly to one row in the `players` database table.
//
// IMPORTANT: This struct contains PasswordHash — a field that must NEVER
// be sent to a client. Always convert to PlayerResponse before writing
// to an HTTP response. See the ToResponse() method below.
type Player struct {
	// ID is the player's unique identifier — a UUID generated by the database.
	// We store it as a plain Go string. Our SQL queries cast UUID to text
	// (id::text) so pgx can scan it into this string field without any
	// special UUID type handling.
	ID string

	// Username is the public display name, shown on leaderboards and team pages.
	// Unique across all players (enforced by a DB UNIQUE constraint).
	Username string

	// Email is the address used for login. Unique across all players.
	Email string

	// PasswordHash is the bcrypt hash of the player's password.
	// bcrypt is a one-way hash — you cannot reverse it to get the plain password.
	// During login we use bcrypt.CompareHashAndPassword to verify the input.
	// The plain password is NEVER stored anywhere in our system.
	PasswordHash string

	// Role is the player's permission tier. Controls what they can do.
	// One of: "player", "team_owner", "moderator", "admin"
	// Enforced both by a DB CHECK constraint and by our middleware.
	Role string

	// ProfilePhotoURL is an optional link to the player's profile picture.
	// It is a *string (pointer to string) rather than a plain string because
	// the database column is nullable — a NULL in the DB becomes nil in Go.
	// nil means "no photo set yet"; a non-nil pointer means there is a URL.
	ProfilePhotoURL *string

	// ClassRole is the player's chosen combat class in the arena game.
	// One of: "tank", "dps", "healer", "support"
	// Also a pointer because it starts as NULL — players choose a class after registering.
	ClassRole *string

	// SkillPointsTotal is the player's total skill point budget.
	// Players spend these on skills. The remaining balance is computed at
	// read time (total minus the sum of allocated skill costs) — we don't store it.
	SkillPointsTotal int

	// Kredits is the player's in-game currency balance.
	// Cannot go below 0 (enforced by a DB CHECK constraint).
	Kredits int

	// CreatedAt is when the player account was first created.
	CreatedAt time.Time

	// UpdatedAt is when the player record was last modified.
	UpdatedAt time.Time
}

// PlayerResponse is a safe, public-facing view of a Player for use in API responses.
// It deliberately omits PasswordHash (which must never leave the server).
//
// The struct tags (e.g. `json:"id"`) tell Go's json package how to name
// the fields in the JSON output. "id" in JSON → ID in Go.
// Without these tags, Go would use the field name as-is (e.g. "ID" not "id").
type PlayerResponse struct {
	ID               string  `json:"id"`
	Username         string  `json:"username"`
	Email            string  `json:"email"`
	Role             string  `json:"role"`
	ProfilePhotoURL  *string `json:"profile_photo_url"`
	ClassRole        *string `json:"class_role"`
	SkillPointsTotal int     `json:"skill_points_total"`
	Kredits          int     `json:"kredits"`
}

// ToResponse converts a Player into a PlayerResponse, dropping sensitive fields.
// This is called a "value receiver" method — (p *Player) means the method is
// defined on a pointer to Player. We use a pointer receiver here because Player
// can be large (many fields), and pointer receivers avoid copying the whole struct.
//
// Always use this when writing player data to an HTTP response.
func (p *Player) ToResponse() *PlayerResponse {
	return &PlayerResponse{
		ID:               p.ID,
		Username:         p.Username,
		Email:            p.Email,
		Role:             p.Role,
		ProfilePhotoURL:  p.ProfilePhotoURL,
		ClassRole:        p.ClassRole,
		SkillPointsTotal: p.SkillPointsTotal,
		Kredits:          p.Kredits,
	}
}

// RegisterRequest is the JSON body the client sends to POST /auth/register.
// The json struct tags map incoming JSON keys to Go struct fields.
type RegisterRequest struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"` // plain text — we hash it in the service before storing
}

// LoginRequest is the JSON body the client sends to POST /auth/login.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// AuthResponse is what we send back after a successful register or login.
// The client stores the Token and sends it in the Authorization header
// of every subsequent request:  Authorization: Bearer <token>
type AuthResponse struct {
	Token  string          `json:"token"`
	Player *PlayerResponse `json:"player"`
}
